export const CHANGE_SELECTED_POINT = "CHANGE_SELECTED_POINT";
export const CHANGE_SELECTED_SERIES_VALUE = "CHANGE_SELECTED_SERIES_VALUE";
export const CHANGE_EXCERCISE_CURRENT_TRAINING =
  "CHANGE_EXCERCISE_CURRENT_TRAINING";

export const CHANGE_TRAINING = "CHANGE_TRAINING";
export const CHANGE_TRAINING_GROUP = "CHANGE_TRAINING_GROUP";
export const CHANGE_TRAINING_GROUP_PART = "CHANGE_TRAINING_GROUP_PART";
export const CHANGE_EXCERCISE = "CHANGE_EXCERCISE";
export const CHANGE_EXCERCISE_DAY = "CHANGE_EXCERCISE_DAY";
export const CHANGE_SERIES = "CHANGE_SERIES";

// export const INIT_REDUX_STATE_FROM_ASYNCSTORAGE =
//   "INIT_REDUX_STATE_FROM_ASYNCSTORAGE";

export default {
  CHANGE_SELECTED_POINT,
  CHANGE_SELECTED_SERIES_VALUE,
  CHANGE_EXCERCISE_CURRENT_TRAINING,
  CHANGE_TRAINING,
  CHANGE_TRAINING_GROUP,
  CHANGE_TRAINING_GROUP_PART,
  CHANGE_EXCERCISE,
  CHANGE_EXCERCISE_DAY,
  CHANGE_SERIES
  // INIT_REDUX_STATE_FROM_ASYNCSTORAGE
};
