export const CHANGE_SELECTED_POINT = "CHANGE_SELECTED_POINT";
export const CHANGE_SELECTED_SERIES_VALUE = "CHANGE_SELECTED_SERIES_VALUE";
export const CHANGE_EXCERCISE_CURRENT_TRAINING =
  "CHANGE_EXCERCISE_CURRENT_TRAINING";

export default {
  CHANGE_SELECTED_POINT,
  CHANGE_SELECTED_SERIES_VALUE,
  CHANGE_EXCERCISE_CURRENT_TRAINING
};
